# prefix 改成 Ctrl-a（更顺手）
unbind C-b
set-option -g prefix C-a
set-option -g default-terminal "screen-256color"  # 启用 256 色
set-option -ag terminal-overrides ",xterm-256color:RGB"

# 分屏用直觉符号
bind-key \\ split-window -h    # \ 竖线 → 垂直
bind-key -  split-window -v    # - 横线 → 水平
# 选择分屏
bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U